version: '3.8'

services:
  backend:
    build:
      context: ./Final-back
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    env_file:
      - .env
    networks:
      - dev-network
    depends_on:
      - db

  frontend:
    build:
      context: ./Final-front
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    env_file:
      - .env
    networks:
      - dev-network
    depends_on:
      - backend

  ml:
    build:
      context: ./Final-ml
    ports:
      - "${ML_PORT:-8000}:8000"
    env_file:
      - .env
    networks:
      - dev-network
    depends_on:
      - backend

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: MONGEUL
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev-network

volumes:
  db_data:

networks:
  dev-network:
    driver: bridge
