version: '3.8'

services:
  backend:
    build:
      context: ./Final-back
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/TEST
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - db

  frontend:
    build:
      context: ./Final-front
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: TEST
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/cnf.d
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
